name: docker-build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Setup
        run: |
          docker-compose -v
          docker-compose up -d
          docker image ls
      - name: Docker clean up 
        run: |
         docker-compose stop
         docker-compose rm -f            
